// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { File } from "./File";
import type { MasterOrFrames } from "./MasterOrFrames";
import type { SessionFingerprint } from "./SessionFingerprint";

export type AstroSession = { uuid: string, fingerprint: SessionFingerprint, lights: Array<File>, darks: MasterOrFrames, flats: MasterOrFrames, biases: MasterOrFrames, };
