// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalibrationStorageMode } from "./CalibrationStorageMode";

export type CalibrateRequest = { storage_mode: CalibrationStorageMode, temp_folder_path: string, };
