// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalibrationProgressStep } from "./CalibrationProgressStep";
import type { CalibrationRunStatus } from "./CalibrationRunStatus";

export type CalibrationProgressMessage = { started_at: bigint, finished_at: bigint | null, status: CalibrationRunStatus, current_step_id: string | null, steps: Array<CalibrationProgressStep>, };
