// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalibrationStepKind } from "./CalibrationStepKind";
import type { CalibrationStepStatus } from "./CalibrationStepStatus";

export type CalibrationProgressStep = { id: string, kind: CalibrationStepKind, label: string, session_uuid: string, session_label: string, count: number, completed_count: number, skipped_count: number, rejected_count: number, status: CalibrationStepStatus, started_at: bigint | null, ended_at: bigint | null, error: string | null, };
