// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NightPrefix } from "./NightPrefix";

export type Config = {
	night_prefixes: Array<NightPrefix>,
	temperature_step: number,
	exposure_step: number,
	gain_step: number,
};
