// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DefaultHeaders = { exposure_time: number | null, gain: number | null, temperature: number | null, };
