// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Nights } from "./Nights";

export type FeState = { nights: Nights, current_preview_file: string | null, };
