// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AstroSession } from "./AstroSession";
import type { File } from "./File";

export type FeState = { raw_nights: { [key in string]: Array<File> }, grouped_nights: Array<AstroSession>, active_grouped_session_uuid: string | null, current_preview_file: string | null, };
