// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DefaultHeaders } from "./DefaultHeaders";
import type { FileType } from "./FileType";
import type { FrameState } from "./FrameState";
import type { ImageStats } from "./ImageStats";

export type File = { path: string, name: string, type: FileType, default_headers: DefaultHeaders, stats: ImageStats | null, calibrated_frame: Array<number> | null, state: FrameState, };
