// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileBatchOperationKind } from "./FileBatchOperationKind";
import type { FileBatchOperationStatus } from "./FileBatchOperationStatus";

export type FileBatchOperationProgressMessage = { started_at: bigint, finished_at: bigint | null, status: FileBatchOperationStatus, operation: FileBatchOperationKind, processed_count: number, total_count: number, current_path: string | null, error: string | null, };
