// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageStats = { star_count: number | null, fwhm: number | null, hfd: number | null, eccentricity: number | null, background_contrast: number | null, quality_score: number | null, };
