// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BayerPattern } from "./BayerPattern";
import type { ImageDataLayout } from "./ImageDataLayout";
import type { ImageOptions } from "./ImageOptions";

export type ImageData = { applied_options: ImageOptions, original_bayer_pattern: BayerPattern | null, depth: number, width: number, height: number, layout: ImageDataLayout, };
