// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageDataLayout } from "./ImageDataLayout";

export type ImageData = { bayer_pattern: string | null, depth: number, width: number, height: number, layout: ImageDataLayout, };
