// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Type } from './Type';

export type NightPrefix = {
	text: string;
	type: Type;
	match_first: boolean;
};
