// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type STFPair = { r: [number, number, number], g: [number, number, number], b: [number, number, number], };
